input_file: 'reddit_posts.csv'
output_file: 'reddit_posts_with_preferences.csv'
batch_size: 4
model: 'gpt-4o-2024-08-06'
samples: 500
system_prompt: >
  You are an 18-year-old CS student studying in America, with interests in philosophy, 
  computer science, and various sports. Rate the given post descriptions based on whether 
  you, as this persona, would like (1) or dislike (0) them. Provide both the index and the rating.